package Image;

import javax.swing.ImageIcon;

import GUI_AND_Function.Driver2;

public class Images {
	public static ImageIcon startscreen = new ImageIcon(Driver2.class.getResource("../images/startscreen.png"));
	public static ImageIcon name = new ImageIcon(Driver2.class.getResource("../images/name1.png"));
	public static ImageIcon name2 = new ImageIcon(Driver2.class.getResource("../images/name2.png"));
	public static ImageIcon mainscreen = new ImageIcon(Driver2.class.getResource("../images/mainscreen.jpg"));
	public static ImageIcon practicescreen = new ImageIcon(Driver2.class.getResource("../images/practicescreen.png"));
	public static ImageIcon gamescreen = new ImageIcon(Driver2.class.getResource("../images/gamescreen.png"));
	public static ImageIcon settingscreen = new ImageIcon(Driver2.class.getResource("../images/settingscreen.png"));
	public static ImageIcon achivementscreen = new ImageIcon(Driver2.class.getResource("../images/achivementscreen.png"));
	public static ImageIcon home = new ImageIcon(Driver2.class.getResource("../images/´ç½ÅÀÌ¸ÅÀÏ°¡´Â°÷.jpg"));
	public static ImageIcon home_one = new ImageIcon(Driver2.class.getResource("../images/home_1.jpg"));
	public static ImageIcon home_two = new ImageIcon(Driver2.class.getResource("../images/home_2.jpg"));
	public static ImageIcon question_mark = new ImageIcon(Driver2.class.getResource("../images/¹°À½Ç¥.jpg"));
	public static ImageIcon question_mark_one = new ImageIcon(Driver2.class.getResource("../images/¹°À½Ç¥_1.jpg"));
	public static ImageIcon question_mark_two = new ImageIcon(Driver2.class.getResource("../images/¹°À½Ç¥_2.jpg"));
	public static ImageIcon ºÏ³èºÏ = new ImageIcon(Driver2.class.getResource("../images/ºÏ³èºÏ.jpg"));
	public static ImageIcon ºÏ³èºÏ_one = new ImageIcon(Driver2.class.getResource("../images/ºÏ³èºÏ_1.jpg"));
	public static ImageIcon ºÏ³èºÏ_two = new ImageIcon(Driver2.class.getResource("../images/ºÏ³èºÏ_2.jpg"));
	public static ImageIcon rabbit = new ImageIcon(Driver2.class.getResource("../images/Åä³¢.jpg"));
	public static ImageIcon rabbit_one = new ImageIcon(Driver2.class.getResource("../images/Åä³¢_1.jpg"));
	public static ImageIcon rabbit_two = new ImageIcon(Driver2.class.getResource("../images/Åä³¢_2.jpg"));
	public static ImageIcon camel = new ImageIcon(Driver2.class.getResource("../images/³«Å¸.jpg"));
	public static ImageIcon camel_one = new ImageIcon(Driver2.class.getResource("../images/³«Å¸_1.jpg"));
	public static ImageIcon camel_two = new ImageIcon(Driver2.class.getResource("../images/³«Å¸_2.jpg"));
	public static ImageIcon dinosaur = new ImageIcon(Driver2.class.getResource("../images/°ø·æ.jpg"));
	public static ImageIcon dinosaur_one = new ImageIcon(Driver2.class.getResource("../images/°ø·æ_1.jpg"));
	public static ImageIcon dinosaur_two = new ImageIcon(Driver2.class.getResource("../images/°ø·æ_2.jpg"));
	public static ImageIcon cherry = new ImageIcon(Driver2.class.getResource("../images/Ã¼¸®.jpg"));
	public static ImageIcon cherry_one = new ImageIcon(Driver2.class.getResource("../images/Ã¼¸®_1.jpg"));
	public static ImageIcon cherry_two = new ImageIcon(Driver2.class.getResource("../images/Ã¼¸®_2.jpg"));
	public static ImageIcon bear = new ImageIcon(Driver2.class.getResource("../images/°õµ¹ÀÌÇª.jpg"));
	public static ImageIcon bear_one = new ImageIcon(Driver2.class.getResource("../images/°õµ¹ÀÌÇª_1.jpg"));
	public static ImageIcon bear_two = new ImageIcon(Driver2.class.getResource("../images/°õµ¹ÀÌÇª_2.jpg"));
	public static ImageIcon captain = new ImageIcon(Driver2.class.getResource("../images/ÈÄÅ©¼±Àå.jpg"));
	public static ImageIcon captain_one = new ImageIcon(Driver2.class.getResource("../images/ÈÄÅ©¼±Àå_1.jpg"));
	public static ImageIcon captain_two = new ImageIcon(Driver2.class.getResource("../images/ÈÄÅ©¼±Àå_2.jpg"));
	public static ImageIcon block = new ImageIcon(Driver2.class.getResource("../images/block5x5.jpg"));
	public static ImageIcon basic = new ImageIcon(Driver2.class.getResource("../images/basic.jpg"));
	public static ImageIcon ban = new ImageIcon(Driver2.class.getResource("../images/ban.jpg"));
	public static ImageIcon manual1 = new ImageIcon(Driver2.class.getResource("../images/manual1.png"));
	public static ImageIcon manual2 = new ImageIcon(Driver2.class.getResource("../images/manual2.png"));
	public static ImageIcon manual3 = new ImageIcon(Driver2.class.getResource("../images/manual3.png"));
	public static ImageIcon pratice1 = new ImageIcon(Driver2.class.getResource("../images/pratice1.png"));
	public static ImageIcon pratice2 = new ImageIcon(Driver2.class.getResource("../images/pratice2.png"));
	public static ImageIcon pratice3 = new ImageIcon(Driver2.class.getResource("../images/pratice3.png"));
	public static ImageIcon pratice4 = new ImageIcon(Driver2.class.getResource("../images/pratice4.png"));
	public static ImageIcon game1 = new ImageIcon(Driver2.class.getResource("../images/game1.png"));
	public static ImageIcon game2 = new ImageIcon(Driver2.class.getResource("../images/game2.png"));
	public static ImageIcon game3 = new ImageIcon(Driver2.class.getResource("../images/game3.png"));
	public static ImageIcon block_flow = new ImageIcon(Driver2.class.getResource("../images/block_flow.png"));
	public static ImageIcon setting1 = new ImageIcon(Driver2.class.getResource("../images/setting1.png"));
	public static ImageIcon achivement1 = new ImageIcon(Driver2.class.getResource("../images/achivement1.png"));
	public static ImageIcon achivement2 = new ImageIcon(Driver2.class.getResource("../images/achivement2.png"));
	public static ImageIcon music_1 = new ImageIcon(Driver2.class.getResource("../images/music1.png"));
	public static ImageIcon music_2 = new ImageIcon(Driver2.class.getResource("../images/music2.png"));
	public static ImageIcon music_3 = new ImageIcon(Driver2.class.getResource("../images/music3.png"));
	public static ImageIcon music_4 = new ImageIcon(Driver2.class.getResource("../images/music4.png"));
	public static ImageIcon size = new ImageIcon(Driver2.class.getResource("../images/puzzlesize.png"));
	public static ImageIcon start = new ImageIcon(Driver2.class.getResource("../images/start.png"));
	public static ImageIcon exit = new ImageIcon(Driver2.class.getResource("../images/exit.png"));
	public static ImageIcon practice = new ImageIcon(Driver2.class.getResource("../images/practice.png"));
	public static ImageIcon game = new ImageIcon(Driver2.class.getResource("../images/game.png"));
	public static ImageIcon manual = new ImageIcon(Driver2.class.getResource("../images/manual.png"));
	public static ImageIcon setting = new ImageIcon(Driver2.class.getResource("../images/setting.png"));
	public static ImageIcon achivement = new ImageIcon(Driver2.class.getResource("../images/achivement.png"));
	public static ImageIcon menuexit = new ImageIcon(Driver2.class.getResource("../images/menuexit.png"));
	public static ImageIcon back = new ImageIcon(Driver2.class.getResource("../images/back.png"));
	public static ImageIcon easy = new ImageIcon(Driver2.class.getResource("../images/5x5.png"));
	public static ImageIcon normal = new ImageIcon(Driver2.class.getResource("../images/10x10.png"));
	public static ImageIcon hard = new ImageIcon(Driver2.class.getResource("../images/20x20.png"));
	public static ImageIcon left = new ImageIcon(Driver2.class.getResource("../images/left.png"));
	public static ImageIcon right = new ImageIcon(Driver2.class.getResource("../images/right.png"));
	public static ImageIcon hidden_1 = new ImageIcon(Driver2.class.getResource("../images/hidden_1.png"));
	public static ImageIcon hidden_2 = new ImageIcon(Driver2.class.getResource("../images/hidden_2.png"));
}
